// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unvkzyztoiirmuevqpyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVudmt6eXp0b2lpcm11ZXZxcHliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTg5NDcsImV4cCI6MjA2MjI5NDk0N30.lFk8L1PITO2RjwUatPqbY2DhZYqc7J59ap3dB5V3YgA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);