// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzldfnkfznrnwbrwpkmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6bGRmbmtmem5ybndicndwa21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTM3MDYsImV4cCI6MjA1ODQ4OTcwNn0.DSxIcIIlr8IYBY-cQzsIYDWoyJyzglylT7EGlbw2AV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);